// tools/thumbs.mjs - packs the title screen's preview images into src/62-thumbs.js.
//
// The images come from the running sim: for each set (#s.<id>) and featured track
// (#t.<code>), let it run a few seconds, draw the canvas into a 384x216 canvas and POST
// its webp data URL to the dev server's /__shot?name=thumb-<key>.webp (keys: the set id,
// or 'f-' + the featured track's id). Then run:  node tools/thumbs.mjs
// It reads docs/screenshots/thumb-*.webp, writes src/62-thumbs.js and deletes the webps.
import { readdir, readFile, writeFile, unlink } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(ROOT, 'docs', 'screenshots');
const files = (await readdir(dir)).filter((f) => /^thumb-.+\.webp$/.test(f)).sort();
if (!files.length) { console.error('no docs/screenshots/thumb-*.webp to pack'); process.exit(1); }
const lines = [];
for (const f of files) {
  const key = f.slice(6, -5);
  const b64 = (await readFile(join(dir, f))).toString('base64');
  lines.push(`  T[${JSON.stringify(key)}] = 'data:image/webp;base64,${b64}';`);
}
const out = `// 62-thumbs.js - small preview images of each set and featured track for the title screen,
// as data: URLs (webp, 384x216). Generated by tools/thumbs.mjs from the running sim; do not
// edit by hand. Regenerate after a set changes its look. Missing keys get a lettered card.
(function (HW) {
  const T = (HW.thumbs = HW.thumbs || {});
${lines.join('\n')}
})(window.HW);
`;
await writeFile(join(ROOT, 'src', '62-thumbs.js'), out);
for (const f of files) await unlink(join(dir, f));
console.log('packed', files.length, 'thumbnails,', Math.round(out.length / 1024), 'KB');
